version: '2.1'

services:
  magento:
    build: ./docker/magento
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
      - elasticsearch

  mysql:
    image: mysql:5.7.26
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: myrootpwd
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200



